# NUMpy array operation

In [2]:
import numpy as np

### INDEXING AND SLICING

In [7]:
# for 1d arrays
arr = np.array([1,2,3,4,5,6,7])
print('basic slicing', arr[1:4])
print('slicing with steps', arr[1:6:2])
print('negative indexing', arr[-2])


basic slicing [2 3 4]
slicing with steps [2 4 6]
negative indexing 6


In [12]:
arr_2d = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

print('specific element', arr_2d[0,0]) # here it starts from 0 , first row and first column starts from zero

print('entire row', arr_2d[0])

print('enitre column', arr_2d[:,0])

specific element 1
entire row [1 2 3]
enitre column [1 4 7]


####  sorting 

In [4]:
unstored_arr = np.array([2,3,4,1,9,8])
print('sorted array', np.sort(unstored_arr))

unstored_2d_arr = np.array([[2,4],[3,6],[1,9]])
print("sorted 2d array by collumn", np.sort(unstored_2d_arr, axis=0))
print("sorted 2d array by rows", np.sort(unstored_2d_arr, axis=1))

sorted array [1 2 3 4 8 9]
sorted 2d array by collumn [[1 4]
 [2 6]
 [3 9]]
sorted 2d array by rows [[2 4]
 [3 6]
 [1 9]]


## filtering

In [5]:
numbers = np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers = numbers[numbers % 2 == 0]
print("even numbers in the list are :" ,even_numbers)


even numbers in the list are : [ 2  4  6  8 10]


## filter by mask

In [6]:
mask = numbers > 5
print("numbers greater than 5", numbers[mask])

numbers greater than 5 [ 6  7  8  9 10]


fancy indexing vs np.where

In [7]:
indices = [1,2,5]
print(indices)

where_result = np.where(numbers > 5)
print( numbers[where_result])

[1, 2, 5]
[ 6  7  8  9 10]


In [15]:
conditions_array=np.where(numbers>5,"true","false")
print(conditions_array)

['false' 'false' 'false' 'false' 'false' 'true' 'true' 'true' 'true'
 'true']


## adding and removing data

In [18]:
arr_1 = np.array([1,2,3])
arr_2 = np.array([4,5,6])

add_arr= arr_1+arr_2
print(add_arr)

combined_arr = np.concatenate((arr_1,arr_2))
print(combined_arr)



[5 7 9]
[1 2 3 4 5 6]


### array compatibility

In [21]:
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([7,8,9,0])

print('compatibility shapes', a.shape == b.shape)
print(b.shape == c.shape)


compatibility shapes True
False


In [26]:
original_arr = np.array([[1,2],[3,4]])
new_row = np.array([5,6])
new_col = np. array([[5],[6]])

with_new_row = np.vstack((original_arr, new_row))
print(with_new_row)

with_new_col = np.hstack((original_arr,new_col))
print(with_new_col)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 5]
 [3 4 6]]


In [28]:
arr= np.array([1,2,3,4,5])
delete = np.delete(arr,3)
print(delete)

[1 2 3 5]
