Numpy array and basics
learn about numpy with chai aur code

In [1]:
import numpy as np

creating array from list

In [2]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array: ", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array: ", arr_2d)

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


List vs numpy array

In [3]:
py_list = [1, 2, 3]
print("Python list multiplication ", py_list * 2)


np_array = np.array([1, 2, 3]) #element wise multiplication
print("Python array multiplication ", np_array * 2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time: ", time.time() - start)

Python list multiplication  [1, 2, 3, 1, 2, 3]
Python array multiplication  [2 4 6]

 List operation time:  0.08008170127868652

 Numpy operation time:  0.008728742599487305


## creating array from scratch

In [10]:
zero_array = np.zeros((3,3))
print(zero_array)
print("")
one_array = np.ones((3,3))
print(one_array)
print("")
const_array = np.full((2,2),5)
print(const_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[5 5]
 [5 5]]


## vector, matrix, tensor

In [17]:
vector = np.array([1,2,3])
print(vector)

matrix = np.array([[1,2,3],
                   [4,5,6]])
print(matrix)

tensor = np.array([[[1,2,3],[4,5,6]],
                  [ [6,7,8], [9,0,1]]])
print(tensor)



[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2 3]
  [4 5 6]]

 [[6 7 8]
  [9 0 1]]]


## array properties

In [6]:
arr = np.array([[1,2,3], 
                [4,5,6]])

print("dimension", arr.ndim)
print("size", arr.size)
print("shape" , arr.shape)
print("type", arr.dtype)

dimension 2
size 6
shape (2, 3)
type int64


### array reshaping

In [2]:
arr = np.arange(9)
print("normal array ", arr )

reshaped_arr = arr.reshape((3,3))
print('reshaped array : ', reshaped_arr)

flattend_arr = reshaped_arr.flatten()
print(' flatened array', flattend_arr)

ravelled_arr = reshaped_arr.ravel()
print("prints the view not copy", ravelled_arr)

transpose_arr = reshaped_arr.T
print('transpossed array ', transpose_arr)

normal array  [0 1 2 3 4 5 6 7 8]
reshaped array :  [[0 1 2]
 [3 4 5]
 [6 7 8]]
 flatened array [0 1 2 3 4 5 6 7 8]
prints the view not copy [0 1 2 3 4 5 6 7 8]
transpossed array  [[0 3 6]
 [1 4 7]
 [2 5 8]]
